[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "lit-movie-diary"
version = "0.1.0"
description = "A Letterboxd-inspired terminal movie diary"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "rich",
    "readchar",
    "requests",
    "python-dotenv",
    "pillow"
]

[project.scripts]
lit = "lit.main:main"

[tool.setuptools.packages.find]
include = ["lit"]